routes:
  # /signup/:
  #   template: members/signup
  #   data: page.signup
  # /signin/:
  #   template: members/signin
  #   data: page.signin
  # /membership/:
  #   template: members/membership
  #   data: page.membership
  # /account/:
  #   template: members/account
  #   data: page.account
  /everything-psg/:
    template: page-category
    data: page.everything-psg
  /series/:
    template: page-category
    data: page.series
  /mixed/:
    template: page-category
    data: page.mixed
  /team/:
    template: page-team
    data: page.team
  /error-301/:
    template: error-301

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /category/{slug}/
  author: /author/{slug}/

